apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  namespace: ${{values.project_name.split('/')[1]}}
  name: ${{values.bucket_name}}
spec:
  forProvider:
    region: ${{values.bucket_region}}
  providerConfigRef:
    name: aws
    kind: ClusterProviderConfig