apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  namespace: ${{values.system.split('/')[1]}}
  name: ${{values.bucket_name}}
  labels:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.bucket_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.bucket_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  forProvider:
    region: ${{values.bucket_region}}
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default