apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  namespace: ${{values.system.split('/')[1]}}
  name: ${{values.bucket_name}}
  annotations:
    backstage.io/kubernetes-cluster: ${{ values.targetCluster }}
spec:
  forProvider:
    region: ${{values.bucket_region}}
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default