apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: ${{values.app_name}}
    app: ${{values.app_name}}
  name: ${{values.app_name}}
  namespace: ${{values.system.split('/')[1]}}
spec:
  selector:
    matchLabels:
      app: ${{values.app_name}}
  podMetricsEndpoints:
    - port: http
      path: "/actuator/prometheus"
      interval: 15s