apiVersion: eks.aws.m.upbound.io/v1beta1
kind: Cluster
metadata:
  name: cheap-cluster
  labels:
    name: cheap-cluster
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
  forProvider:
    region: us-east-1
    roleArnRef:
      name: cluster-role
    version: "1.34"
    vpcConfig:
      subnetIdRefs:
        - name: private-subnet-1
        - name: private-subnet-2
      # Security group for cluster control plane
      securityGroupIdRefs:
        - name: eks-cluster-sg
      # Enable private endpoint so nodes in private subnets can reach cluster
      endpointPrivateAccess: true
      endpointPublicAccess: true
---
apiVersion: eks.aws.m.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: bottlerocket-spot-nodes
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: us-east-1
    clusterNameRef:
      name: cheap-cluster
    nodeRoleArnRef:
      name: node-role
    subnetIdRefs:
      - name: private-subnet-1
      - name: private-subnet-2
    
    # --- COST OPTIMIZATION CONFIG ---
    capacityType: SPOT                # <--- Huge savings (Spot Instances)
    amiType: BOTTLEROCKET_x86_64      # <--- Minimal OS
    instanceTypes:                    # <--- Fallback options for Spot availability
      - t3.medium
      - t3a.medium
      - t2.medium
      - m5.large
    
    scalingConfig:
      desiredSize: 2
      minSize: 1
      maxSize: 3