apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: crossplane-provider-aws
  description: The Crossplane provider for AWS.
spec:
  type: crossplane-provider
  owner: group:default/platform-engineering

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: crossplane-aws-s3-provider
  description: Manages AWS S3 buckets using Crossplane.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - aws
    - s3
    - crossplane
    - infrastructure
spec:
  type: crossplane-xr
  owner: group:default/development
  lifecycle: experimental
  dependsOn:
    # This component depends on a Crossplane provider being installed.
    - resource:default/crossplane-provider-aws
