apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: '${{values.app_description}}'
  annotations:
    github.com/project-slug: zenardi-org/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
  tags:
    - react
    - typescript