apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: '${{values.app_description}}'
  annotations:
    github.com/project-slug: zenardi-org/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
  links:
    - url: http://${{values.domain_name}}
      title: ${{values.app_name}} Link
      icon: dashboard
      type: admin-dashboard
  tags:
    - react
    - typescript
spec:
  type: website
  owner: group:default/development
  lifecycle: experimental