apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: '${{values.app_description}}'
  annotations:
    github.com/project-slug: ${{values.orgName}}/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "title == '${{values.app_name}}'"
    grafana/alert-label-selector: "app=${{values.app_name}}"
  links:
    - url: http://${{values.domain_name}}
      title: ${{values.app_name}} Link
      icon: dashboard
      type: admin-dashboard
  tags:
    - react
    - typescript
spec:
  type: website
  owner: ${{values.owner}}
  lifecycle: experimental