apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  name: cluster-role
  labels:
    role: cluster
    environment: ${{values.app_env}}
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": { "Service": "eks.amazonaws.com" },
            "Action": "sts:AssumeRole"
          }
        ]
      }
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: eks-cluster-policy
  labels:
    environment: ${{values.app_env}}
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    roleRef:
      name: cluster-role
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  name: node-role
  labels:
    environment: ${{values.app_env}}
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": { "Service": "ec2.amazonaws.com" },
            "Action": "sts:AssumeRole"
          }
        ]
      }
---
# Attach required Worker Node policies
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: eks-node-worker
  labels:
    environment: ${{values.app_env}}
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    roleRef:
      name: node-role
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: eks-node-cni
  labels:
    environment: ${{values.app_env}}
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    roleRef:
      name: node-role
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: eks-node-registry
  labels:
    environment: ${{values.app_env}}
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    roleRef:
      name: node-role