apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPC
metadata:
  name: ${{ values.cluster_name }}-vpc
  labels:
    name: ${{ values.cluster_name }}-vpc
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostnames: true
    tags:
      Name: ${{ values.cluster_name }}-vpc

---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: ${{ values.cluster_name }}-igw
  labels:
    name: ${{ values.cluster_name }}-igw
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    vpcIdRef:
      name: ${{ values.cluster_name }}-vpc
    tags:
      Name: ${{ values.cluster_name }}-igw
---
# Public Subnet (Hosts the NAT Gateway)
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: public-subnet-1
  labels:
    name: public-subnet-1
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    vpcIdRef:
      name: ${{ values.cluster_name }}-vpc
    cidrBlock: 10.0.1.0/24
    availabilityZone: ${{ values.eks_region }}a
    mapPublicIpOnLaunch: true
    tags:
      Name: public-subnet-1
---
# Private Subnet (Hosts the Nodes) - AZ 1
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-1
  labels:
    name: private-subnet-1
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    vpcIdRef:
      name: ${{ values.cluster_name }}-vpc
    cidrBlock: 10.0.2.0/24
    availabilityZone: ${{ values.eks_region }}a
    tags:
      Name: private-subnet-1
---
# Private Subnet (Hosts the Nodes) - AZ 2
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-2
  labels:
    name: private-subnet-2
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    vpcIdRef:
      name: ${{ values.cluster_name }}-vpc
    cidrBlock: 10.0.3.0/24
    availabilityZone: ${{ values.eks_region }}b
    tags:
      Name: private-subnet-2
---
# Elastic IP for NAT Gateway
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: EIP
metadata:
  name: nat-eip
  labels:
    name: nat-eip
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    domain: vpc
---
# NAT Gateway (The requested component)
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: ${{ values.cluster_name }}-nat-gw
  labels:
    name: ${{ values.cluster_name }}-nat-gw
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    allocationIdRef:
      name: nat-eip
    subnetIdRef:
      name: public-subnet-1
    tags:
      Name: ${{ values.cluster_name }}-nat-gw
---
# Route Table for Private Subnet (Points to NAT)
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: ${{ values.cluster_name }}-private-rt
  labels:
    name: ${{ values.cluster_name }}-private-rt
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    vpcIdRef:
      name: ${{ values.cluster_name }}-vpc
    tags:
      Name: ${{ values.cluster_name }}-private-rt
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Route
metadata:
  name: private-route-nat
  labels:
    name: ${{ values.cluster_name }}-private-route-nat
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    routeTableIdRef:
      name: ${{ values.cluster_name }}-private-rt
    destinationCidrBlock: 0.0.0.0/0
    natGatewayIdRef:
      name: ${{ values.cluster_name }}-nat-gw
---
# Route Table Association for Private Subnet
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: private-rta
  labels:
    name: private-rta
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    subnetIdRef:
      name: private-subnet-1
    routeTableIdRef:
      name: ${{ values.cluster_name }}-private-rt
---
# Route Table for Public Subnet (Points to IGW)
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: ${{ values.cluster_name }}-public-rt
  labels:
    name: ${{ values.cluster_name }}-public-rt
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    vpcIdRef:
      name: ${{ values.cluster_name }}-vpc
    tags:
      Name: ${{ values.cluster_name }}-public-rt
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Route
metadata:
  name: public-route-igw
  labels:
    name: ${{ values.cluster_name }}-public-route-igw
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    routeTableIdRef:
      name: ${{ values.cluster_name }}-public-rt
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdRef:
      name: ${{ values.cluster_name }}-igw
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: public-rta
  labels:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    subnetIdRef:
      name: public-subnet-1
    routeTableIdRef:
      name: ${{ values.cluster_name }}-public-rt
---
# Route Table Association for Private Subnet 2 (Same route table as subnet-1)
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: private-rta-2
  labels:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
  annotations:
    backstage.io/kubernetes-cluster: ${{values.targetCluster.split('/')[1]}}
    backstage.io/kubernetes-id: ${{values.cluster_name}}
    backstage.io/kubernetes-namespace: ${{values.system.split('/')[1]}}
spec:
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
  forProvider:
    region: ${{ values.eks_region }}
    subnetIdRef:
      name: private-subnet-2
    routeTableIdRef:
      name: ${{ values.cluster_name }}-private-rt