apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{ values.cluster_name }}
  namespace: argocd
spec:
  description: Project for the ${{ values.cluster_name }} AKS cluster
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
